### ISSUE TITLE
Fails to create function

### ISSUE THREAD

**Issue by serh2i** [wix/wix-embedded-mysql#128]
I've found that with this init script:
`create function my_func()
  returns varchar(100)
  begin
    return 'hello';
  end;`

fails initialization with:

`Caused by: com.wix.mysql.exceptions.CommandFailedException: Command 'create function my_func()
  returns varchar(100)
  begin
    return 'hello';
  end;
' on schema 'my_schema' failed with errCode '1' and output 'mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4
'`

Is it expected?
Any idea about reasons / workaround?

The same snippet works with local mysql version 5.7.21 (from brew)
Embedded claims `EmbeddedMysql version 'Version 5.7.19'`
Both under latest macOS.

**Comment by viliusl** [comment]
@serh2i the way I load scripts is via [mysql client](https://github.com/wix/wix-embedded-mysql/blob/master/wix-embedded-mysql/src/main/java/com/wix/mysql/MysqlClient.java#L66) (and not executing smth like `source file` due to a fact that files can be in jars etc.). I guess you stumbled upon stored procedures and delimiter issue: https://dev.mysql.com/doc/refman/5.7/en/stored-programs-defining.html

I don't have immediate fix on my end - tired a quick fix to save sql commands to a temp file and execute via `source {file}`, but then smth else went wrong:/

I will look into it later, but you potentially can do a workaround/fix on your end.

**Comment by serh2i** [comment]
Yes, you were right, that's a delimiter issue :)
Thank you! Closing.

**Comment by viliusl** [comment]
👍
