### ISSUE TITLE
Sometimes EmbeddedMySQL crashes

### ISSUE THREAD

**Issue by pijusn** [wix/wix-embedded-mysql#51]
Today I was getting this error when running ITs:

![screen shot 2016-06-03 at 11 29 58](https://cloud.githubusercontent.com/assets/2745605/15777073/5bae0d1a-2995-11e6-8185-bf5caeba52bb.png)

When it happens, my ITs fail saying environment failed to initialize. Not sure which way causation goes because StackTrace indicates environment shutting down.

Vilius told me to comment out `mysqld.stop()` and it worked. However, now it works with `mysqld.stop()` as well.

Managed service used:

```
class MySqlManagedService(config: MysqldConfig, dbSchema: SchemaConfig) extends ManagedService {
  private var mysqld: EmbeddedMysql = _

  override def start(): Unit = mysqld = anEmbeddedMysql(config).addSchema(dbSchema).start()

  override def stop(): Unit = mysqld.stop()

  def reload(): Unit = mysqld.reloadSchema(dbSchema)
}
```

This seems like a race condition. It's up to you whether to investigate it or not. This might be too little information to go on.

If I manage to reproduce it, will post again.

**Comment by viliusl** [comment]
@pijusn - this issue is valid (there is a bug:)), but it should not cause errors that would intervene with process shutdown or throw exceptions, as whole mysqld shutdown procecude is mostly best-effort - try like 5 ways of shutdown, but none of them throws error. Error you see is just logged as WARN, but swallowed and does not result in a throw.

I see possible issue, but need to think of a way to solve it. Shutdown happens https://github.com/wix/wix-embedded-mysql/blob/master/src/main/java/com/wix/mysql/MysqldProcess.java#L69 and regardless if it's synchronized, there is a wait() in https://github.com/wix/wix-embedded-mysql/blob/master/src/main/java/com/wix/mysql/io/NotifyingStreamProcessor.java#L71 that can cause lock to be released and shutdownhook thread to pick it up. There is a stopped variable in AbstractProcess that is not volatile, so this race condition is possible.

Will have to think how to solve it - do a PR to flapdoodle process or locally.

Anyway, thanks for issue report:)

**Comment by viliusl** [comment]
@pijusn - closing as I did not get any additional reports. Spring cleanup:)
