### ISSUE TITLE
Error 206 (windows) when adding a big schema

### ISSUE THREAD

**Issue by benjamin84** [wix/wix-embedded-mysql#62]
The MysqlClient seems to just put the whole sql dump file into the commandline of the mysql client. On windows (maybe on linux, too) there is a limit on how long a commandline can be.

A better way should be to write the script content into stdin of the process.

Here's a little patch which should do that work:

[MysqlClient-patch.txt](https://github.com/wix/wix-embedded-mysql/files/420385/MysqlClient-patch.txt)

Note that this solution does not handle sql files which contain "SET NAMES ..." with any other charset than UTF-8 incorrectly.

**Comment by viliusl** [comment]
@benjamin84 - so you say 'SET NAMES' was working properly for previous (somewhat lame) impl, but will not for your proposed one?

**Comment by benjamin84** [comment]
Sorry it was a typo. The previous way did not handle different charsets correctly, too. The reason is that the content of the sql script is read into a string and supplied to the mysql process using the system default encoding (losing portability, encoding errors, etc). Best way is to refactor the code to use byte arrays instead of strings to supply the file content to the mysql process.

**Comment by cullenjohnson** [comment]
This is still an issue for me in Windows 10 x64. I've stepped through with a debugger and even though I'm sending a properly formatted  large SQL string into MysqlClient.execute(), but the call to `IOUtils.copy(new StringReader(sql), p.getOutputStream(), Charset.defaultCharset());` doesn't seem to be copying the entire SQL string. Perhaps this function is dependent on available system memory? I would suggest iterating through the string line by line and writing it directly to `process.getOutputStream()`, rather than trying to copy the entire string all at once.

**Comment by benjamin84** [comment]
There shouldn't be a problem with `IOUtils.copy` because it buffers the data internally so there won't be too much data in memory. What is the error message from the mysql client?

**Comment by cullenjohnson** [comment]
There isn't an error immediately, but the stored procedure that I set up in my sql is not available when I try to call it subsequently. I can't post the actual SQL I use since it uses customer data, but the SQL file looks like this:

http://pastebin.com/U0gi4Pbf

When I later run `CALL setup_test_fixture();`, I get: `com.wix.mysql.exceptions.CommandFailedException: Command '"CALL setup_test_fixture();"' on schema 'schema' failed with errCode '1' and output 'ERROR 1265 (01000) at line 1: Data truncated for column 'column_name' at row 1`.

Now that I'm thinking about it, Windows may just be truncating the line for the process output stream. I'll see if modifying line length will fix the problem and get back to you.

**Comment by benjamin84** [comment]
Looks like a encoding problem with your data. The file is read in utf8 encoding and supplied to the console as a utf8 encoded byte string. So if your file is not properly encoded in utf8 or the server has a somewhat strange default encoding for the client connection there is a strong possibility that such errors like 'data truncated for column xy at 123' occur because some messed up chars force mysql to ignore those values.

**Comment by cullenjohnson** [comment]
Thanks for replying. The file was already in UTF-8 format, but I saved it again in Sublime Text to UTF-8 encoding, but it didn't seem to make a difference. :/ I'm wondering if it has to do with escaped apostrophes inside strings? In the SQL file, some of the columns have contractions like `'don\'t'`... I'm wondering if maybe need any further encoding since they're being copied directly into an output stream?

**Comment by benjamin84** [comment]
The way the file is loaded into the DB is similar to this command on a shell:

`mysql -u someuser -ppassword databasename < dump.sql`

Maybe you try to import the file this way on a testmachine. As this is a bit off topic you can contact me directly for further support. If there is a bug that caused your problem we can file that issue here again.
